version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'ingimar'
      MYSQL_PASSWORD: 'ingimar'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    #expose:
    #  - '13306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

#mysql -u root -p -h 127.0.0.1
